[build]
  command = "yarn lambda:build && yarn build && yarn export"
  publish = "out"
  functions = "lambda"
[[headers]]
  for = "*.avif"
  [headers.values]
    Content-Type = "image/avif"
    Content-Disposition = "inline"